baseURL = "https://bonnee.github.io/"
languageCode = "en-us"
title = "Bonnee's space"
theme = "anubis"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 2
  
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 3

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  favicon="https://github.com/Bonnee.png?size=64"
  author= "Matteo Bonora"
  email= "bonora.matteo@gmail.com"
  description= "Bonnee's space"
  paginationSinglePost= false
  style="dark-without-switcher"
  readMore= false
  mainSections=["blog", "projects"]