name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: Bonnee/Bonnee.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        HUGO_ENV: production
        TZ: Europe/Rome
